language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ZDw8k9Cf4zNWXJP+Yf5dMEZl2Z2vA6eYvrbgAl5eIOnsBPpdl4WzKTG4eGBP4YBfgO7lhI8MZHA9cCYy3qWGRO/hAfpwzMhmY1CVxxzt4l0xqqIyNns8Z2SY77DUHJQf3bN/ePaU0dFJuzv4KoqK1kobE1sFx+GE6ogOXWSG8x0z+eT35indRVOw1jmhcNxEX9Z7mVXrdZgFXPwGpFIa0uJWbWawPeYP9KreFUMRUSeSsJhfaFM9FnbHB/8sJPgq+3Qih5UyCR2zQfehTE30uU0QXF8UQbqVrpN7NNhXrsQQ7047x9SJ651yKzLRfyiZJJEpBu8HMYKnYgEQR5CR+ygT6RnH9xJV04NA3+JAcZm8haJGtwf5mn+ET1en532QZQ0tfvYPs/kuFA4XMoN9vSqyvf8O4WygqB9RmJk4PPJErH18+6AyFLTNFaTDd1jnJnoa2pT48Ag4PGam03ukOMCrnJio/VUp3Oe7KxUaQlJOJ8/yYWq65ekHKjOOcv7sI4jysimuKUmT0n37iDKndUZPGy7D/kszGV6Ph4AsRESneI51zUszBYK7hvpP7xBMxosaaRxwsIJcEGrfVCWXDWoaVNPW/mjF8+3ccZW1MjVBEDDWl1Wf1uuykEo16YSytCbik1rMn6NTipkEsRy+xYvEMju4N3UAMmXU6td7wVs=
  app: amyspeed-backend
  on:
    repo: amyspeed/amyspeed-backend
  skip_cleanup: 'true'
